### ISSUE TITLE
How to install and get it working

### ISSUE THREAD

**Issue by joaopequeno-git** [simonhq/accu_allergies#1]
Hello,

The instructions are not clear, since i'm for a week trying to get this working.
Please help.
I have installed trough HACS, also installed appdaemon.
On appdaemon added this:
system_packages: []
python_packages:
  - bs4
init_commands: []

This part of the code adapated to my region:
accu_allergies:
  module: accu_allergies
  class: Get_Accu_Allergies
  ACC_FILE: "./allergies"
  ACC_FLAG: "input_boolean.get_allergies_data"
  DEB_FLAG: "input_boolean.reset_allergies_sensor"
  URL_ID: "21921"
  URL_CITY: "canberra"
  URL_COUNTRY: "au"
  URL_LANG: "en"

I have placed it on the apps.yaml in the config folder, but the sensors never show up after restart hass on the Developer tools/States.

What i'm doing wrong?

**Comment by simonhq** [comment]
Hi Joaopequeno,

I have made some changes as it appears the website changed its layout a little, and added a daily schedule to run each morning.

It looks like you have set it up right (bit hard to see the indenting), if you use the 'insert code' button when pasting into here, it will keep the indenting and the like.

Let me know if the new version helps. 

Simon

**Comment by joaopequeno-git** [comment]
i'm still not seeing the sensors indicated.
Do i have to do something mora?

**Comment by simonhq** [comment]
Are you getting any errors in the appdaemon logs?

**Comment by joaopequeno-git** [comment]
I got it working.
For who never user appdaemon the instruction to add this is not clear.
But now i got it working
thanks

**Comment by frayberen** [comment]
I still can't get it to work and I can't find the problem. Maybe it's the AppDaemon settings? It is the first time that I use it. A help please ?? I have special interest in getting it. Thank you!!

**Comment by simonhq** [comment]
Hello joaopequeno,

I am glad you got it working, can you recommend where the instructions need to be improved so that it is easier for people to setup?

Hello frayberen

Can you explain what you have done and what your logs are saying so we can investigate please?

Simon.

**Comment by frayberen** [comment]
Finally, I was able to get it to work properly. Everything has been a bit strange, but now it works. Thank you!! Greetings.

**Comment by simonhq** [comment]
Great.

**Comment by spider7611** [comment]
```
AppDaemon configuration
You will also need to install Beautiful Soup / bs4 by adding bs4 to your python packages in Appdaemon.

system_packages: []
python_packages:
  - bs4
init_commands: []

```
This isnstruction is not clear for me. How to do this? Where is the AppDaemon and how to install bs4?

**Comment by simonhq** [comment]
Hi Spider7611

The code runs in appdaemon, if you have not installed the appdaemon 4 add-on via the supervisor panel you will not be able to use this automation.

I suggest you go and read up how to install the appdaemon 4 add-on. Once you have that installed, this may make more sense. Let me know how you go.

Simon.

**Comment by spider7611** [comment]
Where is the supervisor panel? :) I run the home assistant from docker if it say something.

**Comment by simonhq** [comment]
If you have chosen Home Assistant in Docker, you will need to install AppDaemon on Docker separately and then configure them to work together. 

Try: https://appdaemon.readthedocs.io/en/latest/INSTALL.html

I have not done this as I run a version of this -

https://community.home-assistant.io/t/installing-home-assistant-supervised-on-ubuntu-18-04-04/200020

Which includes the ability to load add-ons, including appdaemon.

Simon
