### ISSUE TITLE
Component error: accu_allergies - Integration 'accu_allergies' not found.

### ISSUE THREAD

**Issue by Spaka30** [simonhq/accu_allergies#10]
I did everything like documentation said but when I put code in config.yaml and check config I get this message "Component error: accu_allergies - Integration 'accu_allergies' not found."
I opened appdaemon file and there is in app accu_allergies.py

I dont know what is the problem here.

**Comment by simonhq** [comment]
Hi Spaka30,

This isn't an 'integration', it is an appdaemon app, so it won't appear in your integration list. 

If you have the got py file in the right place and have added the config to your appdaemon/apps/apps.yaml (nothing needs to go in a config.yaml), added the bs4 python package to your appdaemon configuration and restarted appdaemon then the sensors will be created and be available for you to add to lovelace cards.

Hope this helps

Simon.

**Comment by Spaka30** [comment]
My bad for thinking that config was needed to be added to config.yaml
Thank you for pointing me into the right direction. 
Keep up the good work!
