### ISSUE TITLE
Error pollendata

### ISSUE THREAD

**Issue by Ricks88** [simonhq/accu_allergies#11]
Hello,

The pollen data, mold and dust, give the same value:

![errordata](https://user-images.githubusercontent.com/91467918/143486012-e2516dbd-4200-4260-a29b-b8d22590fe38.png)

All give the ambrosiapollen data instead of the correct one.

![correctdata](https://user-images.githubusercontent.com/91467918/143486155-a0da26fc-9d2a-4821-96c5-bce3b13fd2a8.png)

**Comment by simonhq** [comment]
Hi Ricks88

I have just checked the accuweather website and it appears that they have removed the pollen information for my area, so that url is defaulting the the dust and dander for all of the pollen options, thus giving the same information.

It appears that your area still has them, but can you translate the headings on your screenshot please and let me know the url that yours is using, and I will have a look.

Thanks

Simon

**Comment by Ricks88** [comment]
Hello simonhq,

I think i have found the problem for me, I removed the "URL_POSTCODE:" and after a restart it shows the correct data now.
Maybe the Postcode caused the error?

PS the headings:
ragweed-pollen, grass-pollen, tree-pollen, mold, dust-dander.

Greetings
Rick

**Comment by Ricks88** [comment]
Hi Simon,

Is it maybe possible to add UV-Rates?

Also i tried making some colorfull overview. Maybe some users like it, do you know where i can best place/share the code?

Screenshot:

![overview1](https://user-images.githubusercontent.com/91467918/147270114-2f43e691-9742-468d-9df9-37eaf5c68222.png)
![overview2](https://user-images.githubusercontent.com/91467918/147270117-2643a04b-e341-4c83-acae-5a226b672157.png)

Greetings,
Rick

**Comment by simonhq** [comment]
Hi Ricks,

Those coloured versions look good, if you want to put the code here I can put it in the readme with you attributed?

In terms of UV rates, as it is all screen scraping I am a little hesitant to add any more attributes, personally I get UV rates from this integration (https://www.home-assistant.io/integrations/openuv) and it works well.

Simon

**Comment by Ricks88** [comment]
> 

Hello,

Thanks for the respond.
I will try the Openuv, thanks!


Here is my code:

`type: custom:stack-in-card
mode: vertical
cards:
  - type: horizontal-stack
    cards:
      - type: entities
        entities: []
        title: 'Vandaag - Luchtkwaliteit:'
        state_color: true
  - type: horizontal-stack
    cards:
      - color_type: blank-card
        type: custom:button-card
        styles:
          card:
            - height: 130px
            - margin: 0px
      - type: custom:button-card
        entity: sensor.air_quality_today_names
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Luchtkwaliteit Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_air_today
                  name: Luchtkwaliteit Vandaag
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_air_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Luchtkwaliteit
        color_type: icon
        show_state: true
        custom_fields:
          AirValue:
            card:
              type: custom:button-card
              entity: sensor.acc_air_today
              show_name: false
              show_state: true
              show_entity_picture: false
              show_icon: false
              color_type: card
              color: rgba(255,255,255,0.9)
              tap_action:
                action: none
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent;
                  font-size: 16px !important;
                  font-color: rgba(255,0,0,0.9) !important;
                }
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 10px
            - font-size: 16px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 16px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - margin: 0px
          icon:
            - width: 65px
            - margin-top: 13px
          custom_fields:
            AirValue:
              - align-self: start
              - position: absolute
              - left: 65%
              - top: 55px
              - width: 45px
              - font-size: 16px
              - font-family: Sans-serif
              - text-transform: capitalize
        state:
          - value: Uitstekend
            icon: mdi:air-purifier
            color: rgba(0,231,161,0.9)
          - value: Redelijk
            icon: mdi:air-purifier
            color: rgba(255,191,61,0.9)
          - value: Slecht
            icon: mdi:air-purifier
            color: rgba(255,104,58,0.9)
          - value: Ongezond
            icon: mdi:air-purifier
            color: rgba(255,0,86,0.9)
          - value: Zeer Ongezond
            icon: mdi:air-purifier
            color: rgba(214,38,165,0.9)
          - value: Gevaarlijk
            icon: mdi:air-purifier
            color: rgba(160,56,247,0.9)
      - color_type: blank-card
        type: custom:button-card
        styles:
          card:
            - height: 130px
            - margin: 0px
  - type: custom:gap-card
    height: 20
  - type: entities
    entities:
      - type: divider
    title: ''
    state_color: true
  - type: horizontal-stack
    cards:
      - type: entities
        entities: []
        title: 'Vandaag - Allergieën:'
        state_color: true
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: sensor.acc_ragweed_pollen_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Ambrosiapollen Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_ragweed_pollen_today
                  name: Ambrosiapollen
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_ragweed_pollen_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Ambrosiapollen
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_grass_pollen_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Graspollen Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_grass_pollen_today
                  name: Graspollen
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_grass_pollen_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Graspollen
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_tree_pollen_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Boompollen Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_tree_pollen_today
                  name: Boompollen
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_tree_pollen_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Boompollen
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_mold_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Schimmelsporen Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_mold_today
                  name: Schimmelsporen
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_mold_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Schimmelsporen
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_dust_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Huisstofmijtgehalte Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_dust_today
                  name: Huisstofmijtgehalte
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_dust_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Huisstofmijtgehalt
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
  - type: custom:gap-card
    height: 20
  - type: entities
    entities:
      - type: divider
    title: ''
    state_color: true
  - type: horizontal-stack
    cards:
      - type: entities
        entities: []
        title: 'Vandaag - Kans op:'
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: sensor.acc_common_cold_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Verkoudheidkans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_common_cold_today
                  name: Verkoudheidkans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_common_cold_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Verkoudheid
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_flu_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Griepkans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_flu_today
                  name: Griepkans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_flu_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Griep
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_asthma_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Asthmakans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_asthma_today
                  name: Asthmakans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_asthma_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Asthma
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_arthritis_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Arthritiskans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_arthritis_today
                  name: Arthritiskans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_arthritis_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Arthritis
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_migraine_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Migrainekans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_migraine_today
                  name: Migrainekans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_migraine_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Migraine
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 55px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
      - type: custom:button-card
        entity: sensor.acc_sinus_today
        aspect_ratio: 0
        tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            title: Sinushoofdpijnkans Vandaag
            style:
              hui-vertical-stack-card:
                $hui-entities-card$: |
                  #states {
                    padding-top: 0.5em;
                    padding-bottom: 1.2em;
                  }
            card:
              type: vertical-stack
              cards:
                - type: entity
                  entity: sensor.acc_sinus_today
                  name: Sinushoofdpijnkans
                - type: entities
                  card_mod:
                    class: content
                  entities:
                    - type: custom:gap-card
                      height: 10
                    - entity: sensor.acc_sinus_today_info
                      name: Info
                    - type: custom:gap-card
                      height: 10
              style: |
                ha-card {
                  box-shadow: none;
                  background: transparent !important;
                }
        name: Sinushoofdpijn
        color_type: icon
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - height: 130px
            - margin: 0px
          name:
            - align-self: start
            - position: absolute
            - top: 7px
            - font-size: 14px
            - font-weight: bold
            - font-family: Sans-serif
          img_cell:
            - align-self: start
            - position: relative
            - margin: 0px
          state:
            - align-self: start
            - position: relative
            - font-size: 14px
            - font-family: Sans-serif
            - font-color: rgba(255, 0, 0, 0.8)
            - text-transform: capitalize
            - padding-bottom: 1px
          icon:
            - width: 45px
            - margin-top: 18px
        state:
          - value: 0
            color: rgba(103,251,135,0.8)
          - value: 1
            color: rgba(192,243,106,0.9)
          - value: 2
            color: rgba(255,191,61,0.7)
          - value: 3
            color: rgba(255,129,44,0.7)
          - value: 4
            color: rgba(255,122,42,0.8)
          - value: 5
            color: rgba(255,101,37,0.8)
          - value: 6
            color: rgba(252,99,79,0.9)
          - value: 7
            color: rgba(254,59,59,0.8)
          - value: 8
            color: rgba(254,44,44,0.8)
          - value: 9
            color: rgba(253,12,69,0.8)
          - value: 10
            color: rgba(253,12,93,1.0)
  - type: custom:gap-card
    height: 20
  - type: entities
    entities:
      - type: divider
    title: ''
    state_color: true
style: |
  ha-card {
    width: 100% !important;
    margin: 0px 0px 0px -5px
  }
`

**Comment by Ricks88** [comment]
Template sensor:
`
# Creates a info sensor from the Allergie Attribute (allergy pharse)
#
platform: template
sensors:
  # Air Quality
  acc_air_today_info:
    value_template: "{{ state_attr('sensor.acc_air_today', 'today_air_phrase') }}"
    friendly_name: Air Quality Today Info
    icon_template: mdi:information-outline
  acc_air_tomorrow_info:
    value_template: "{{ state_attr('sensor.acc_air_tomorrow', 'tomorrow_air_phrase') }}"
    friendly_name: Air Quality Tomorrow Info
    icon_template: mdi:information-outline

`

**Comment by Ricks88** [comment]
template:
`---
#
# Creates a state from the acc_air_today value, for colored icons
#
sensor:
  name: Air Quality Today Names
  state: >
    {% set quality = states('sensor.acc_air_today')|float(0) %}
    {% if quality > 249 %}
      Gevaarlijk
    {% elif 249 >= quality > 149 %}
      Zeer Ongezond
    {% elif 149 >= quality > 99 %}
      Ongezond
    {% elif 99 >= quality > 49 %}
      Slecht
    {% elif 49 >= quality > 19 %}
      Redelijk
    {% elif 19 >= quality > 0 %}
      Uitstekend
    {% else %}
      Onbekend
    {% endif %}
`

**Comment by Ricks88** [comment]
Hi @simonhq 

I have a question about your health triggers. Can't find these options/entities and I saw that I need to create input_booleans, but i do not know how to do that. Never worked with input booleans yet.
Can you maybe give me an example or some tips to start with?

**Comment by simonhq** [comment]
Hi Ricks,

If you go to Configuration -> Automation & Scenes -> Helpers -> Add Helper 

If you then select 'Toggle' - this is the new way to create an input_boolean from the front end.

This is then a 'switch' that you can use in anything else that you need an on/off switch for.

Hope this helps

Simon.

**Comment by lubo1953** [comment]
Simon,

it appear that my local accu weather no loner sends out a value for the sensors, but uses high, medium, and low. is there a way to convert the current output to a value for the sensors? right now I'm seeing unknown for all but the air quality which is still reported out as a value.

Lou

**Comment by rononline** [comment]
@Ricks88 That looks very nice! Your config, can you share the "real yaml" code? The markup is now not correct.

**Comment by rononline** [comment]
@Ricks88 maybe share it on https://gist.github.com ??

**Comment by Ricks88** [comment]
> @Ricks88 That looks very nice! Your config, can you share the "real yaml" code? The markup is now not correct.

I will try!

**Comment by Ricks88** [comment]
> @Ricks88 maybe share it on https://gist.github.com ??

maybe this:

https://gist.github.com/Ricks88/7d60ebfa161546c750bfe2b6e6972422

?

**Comment by rononline** [comment]
With that I can create something indeed. Thanks @Ricks88 !!!
