### ISSUE TITLE
National characters

### ISSUE THREAD

**Issue by grzech1983** [simonhq/accu_allergies#18]
Hello,

can you take a look at opening city names with national characters in them? Like:

https://www.accuweather.com/pl/pl/gorzów-wielkopolski/274270/allergies-weather/274270

"ó" in url causes to URL being corrupted (logs from appdaemon):

2023-02-20 13:15:41.109596 INFO accu_allergies: request https://www.accuweather.com/pl/pl/gorz��w-wielkopolski/66-400/asthma-weather/274270

when you open URL:

https://www.accuweather.com/pl/pl/gorz��w-wielkopolski/66-400/asthma-weather/274270

in browser it will not load any data and instead of that it will redirect you to proper URL.

Thanks

**Comment by simonhq** [comment]
Hi Grzech,

I will have a look at this, it must be something to do with the url encoding, I will do a little research, and get back to you.

Thanks

Simon
