### ISSUE TITLE
Does not create sensors?

### ISSUE THREAD

**Issue by Hoekeren** [simonhq/accu_allergies#2]
Hi. 
I am runnging Hasio on a rasperryPi 4b+
i hav etried to install yor automation add-on from HACS
Afterwords I have added this:

system_packages: []
python_packages:
  - bs4
init_commands: []

(dont mind the formatting)
to my /config/appdaemon/appdaemon.yaml

and restart. 

But neither sensor.acc.......... nor booleans are created?

I musst be doing something wrong. 
I hope you are able to helt my.
Kind regards 
Christian

**Comment by simonhq** [comment]
Hi Christian,

That instruction isn't for the appdaemon.yaml, it is for the configuration page of appdaemon on the add-ons page of Hassio.

![appdaemon-config](https://user-images.githubusercontent.com/18653928/82800915-d2c09500-9ebf-11ea-983a-10897722905e.PNG)

You don't need to add anything to appdaemon.yaml, but you will need to add the correct configuration to your apps.yaml.

Simon.

**Comment by Hoekeren** [comment]
Thanx alot, now it runnig perfectly.

I look forward to using it in my automations. We are a family with grass allergy, så beeing prompted to take our preventive medicin before leaving for schoole and work will be great.
