### ISSUE TITLE
Quit working HA 116

### ISSUE THREAD

**Issue by jscherry** [simonhq/accu_allergies#5]
Getting errors in appdaemon now. Worked great up until 116 upgrade. May have something to do with Python upgrade to 3.8?

**Comment by RenfoJu1** [comment]
It stopped to me as well and am still on 115.6, so not related to 116. Maybe something happened in server side?

**Comment by simonhq** [comment]
Hi all,

It appears that accu_weather has changed the way that it generates it's website, before there was a set of JSON that I could parse at the top of each page with all the information that was used on the page. This no longer appears, so I will need to investigate how it is put together. 

I am trying to steer clear of 'screen scraping' per se as it is much more difficult to maintain, but I will have a look and decide if this is able to be done.

Simon.

**Comment by simonhq** [comment]
I believe that I have resolved this now, please update through HACS and let me know if you have any more issues.

**Comment by iainp999** [comment]
All good here @simonhq - thanks!
