### ISSUE TITLE
input_boolean flags needed in documentation

### ISSUE THREAD

**Issue by mmartoccia** [simonhq/accu_allergies#7]
Greetings! Can you please update the names of the input_boolean that are being watched by the app?  I've looked through the code and suspect that its acc_flag and deb_flag but am unsure.  May also help others.  Appreciate the effort and this App well done!

**Comment by simonhq** [comment]
Hi mmartoccia,

I am a little unsure of what you want me to update? in the documentation I have the ACC_FLAG and DEB_FLAG needing to be provided in the apps.yaml file, you add in the names of the input booleans against these variables and they will be watched.

Can you let me know where I can make it clearer please?

Simon.
